// The Markdown view — the ledger as a committed file.
//
// The one view with no scripting behind it, so everything a reader
// needs is in the text itself. Header contract: `../views.mjs`.

import { TICKET_RE, orderClosed, orderOpen } from "../core.mjs";
import { counts, ticketUrlOf } from "./html.mjs";
import { summary } from "./summary.mjs";

// ----------------------------------------------------------- markdown

// GitHub renders Markdown on the repo page and sanitizes the HTML in
// it: `<details>`, tables and links survive; `<style>`, `<script>`,
// `class` and `style` do not. So this view carries no CSS and no script.
const BLOCKS = "▁▂▃▄▅▆▇█";


/**
 * A progress bar out of block glyphs.
 *
 * Plain text, so it survives sanitizing, renders in any font, and needs
 * no image host — which a private repo could not use anyway.
 */
export function bar(pct, width = 10) {
  const value = Math.max(0, Math.min(100, pct));
  const filled = Math.floor((value * width) / 100);
  const remainder = Math.floor((((value * width) % 100) * BLOCKS.length) / 100);
  let out = "█".repeat(filled);
  if (filled < width && remainder) out += BLOCKS[remainder - 1];
  // Pad with a light shade rather than blanks: an empty bar should read
  // as nothing done, not as a missing bar.
  return out + "░".repeat(width - [...out].length);
}


function mdLinks(text, turl) {
  return String(text).replace(TICKET_RE, (match) => {
    const cut = match.lastIndexOf("#");
    return `[${match}](${turl(match.slice(0, cut), match.slice(cut + 1))})`;
  });
}


function mdRef(thread, codes, turl) {
  const ticket = thread.ticket;
  if (!ticket) return "`NO TICKET`";
  const cut = ticket.lastIndexOf("#");
  const [repo, number] = [ticket.slice(0, cut), ticket.slice(cut + 1)];
  const label = codes[repo] ?? repo;
  return `[\`${label}#${number}\`](${turl(repo, number)})`;
}


/** The waiting-on cell: what holds the thread, and why. */
function mdState(thread, turl) {
  if (thread.blocked) {
    const label = {
      principal: "**blocked · you**",
      internal: "blocked",
      external: "external",
    }[thread.blocked.on];
    return `${label} — ${mdLinks(thread.blocked.what, turl)}`;
  }
  if (thread.parked) return `parked — trigger: ${mdLinks(thread.parked, turl)}`;
  return "";
}


/**
 * The ledger as Markdown, for GitHub to render on the repo page.
 *
 * A second VIEW of the same fold, never a second source: this and the
 * page both call `fold()`, so they cannot disagree about what is open.
 */
export function renderMarkdown(threads, title, nowMsg = null, codes = {}, generated = "", sessionUrl = null, forge = {}) {
  const open = orderOpen(threads);
  const closed = orderClosed(threads);
  const n = counts(open, closed);
  const turl = ticketUrlOf(forge);

  const lines = [
    "<!-- Generated by the thread-ledger skill. Edits here are",
    "     overwritten on the next push; the events in ledger/ are",
    "     the source. -->",
    "",
    `# ${title}`,
    "",
    `**${n.active} active · ${n.onYou} blocked on you · ${n.waiting} waiting · ` +
      `${n.parked} parked · ${n.done} done**`,
    "",
  ];
  if (generated) lines.push(`<sub>generated ${generated}</sub>`, "");

  lines.push("| | Thread | Waiting on |", "| --- | --- | --- |");
  for (const thread of open) {
    const indent = thread.depth ? "↳ " : "";
    // The title carries the link to the conversation the thread was
    // last touched in — per thread, because a ledger outlives any one
    // session and threads get picked up in later ones.
    let titleText = thread.title ?? thread.thread;
    const url = thread.url ?? sessionUrl;
    if (url) titleText = `[${titleText}](${url})`;
    let cell = `${indent}${mdRef(thread, codes, turl)} ${titleText}`;
    if (thread.note) {
      cell += `<details><summary>note</summary>${mdLinks(thread.note, turl)}</details>`;
    }
    lines.push(`| \`${bar(thread.pct ?? 0)}\` | ${cell} | ${mdState(thread, turl)} |`);
  }

  if (closed.length) {
    lines.push("", "---", "", "### Done", "");
    for (const thread of closed) {
      const mark = thread.state === "completed" ? "x" : " ";
      let text = thread.title ?? thread.thread;
      if (thread.state === "dropped") text = `~~${text}~~`;
      const url = thread.url ?? sessionUrl;
      if (url) text = `[${text}](${url})`;
      const suffix = thread.note ? ` — ${thread.note}` : "";
      lines.push(`- [${mark}] ${mdRef(thread, codes, turl)} ${text}${suffix}`);
    }
  }
  return lines.join("\n") + "\n";
}
