// Reading forge traffic out of a transcript.
//
// Review comments, ticket writes and reference notation all have to be
// recognized from the tool calls a turn made, because the forge itself
// is not reachable from here. Pure and browser-safe.

/**
 * The attribution footer every Claude-authored forge post carries.
 *
 * The discriminator for the review-persistence question: a
 * fetched comment body WITHOUT this line was written by a human, and
 * what a human wrote in a review is exactly the content that must not
 * live only in a discarded transcript.
 */
export const ATTRIBUTION_FOOTER = "_Generated by [Claude Code](https://claude.ai/code)_";


const REVIEW_FETCH = /(pull_request_read|issue_read)$/;

const REVIEW_METHODS = new Set(["get_review_comments", "get_reviews", "get_comments"]);

const BODY_FIELD = /"body"\s*:\s*"((?:[^"\\]|\\.)*)"/g;


/**
 * Comment `{ body, author }` pairs in one chunk of fetched text.
 *
 * Parsed as JSON where the chunk is JSON — tool results are — so the
 * author stands next to its own body rather than being regex-guessed
 * across a flat string. Chunks that do not parse fall back to the
 * body-field regex with the author unknown.
 */
function commentsIn(chunk) {
  let parsed;
  try {
    parsed = JSON.parse(chunk);
  } catch {
    return [...chunk.matchAll(BODY_FIELD)].map(([, body]) => ({ body, author: null }));
  }
  const found = [];
  const walk = (node) => {
    if (Array.isArray(node)) {
      for (const item of node) walk(item);
      return;
    }
    if (!node || typeof node !== "object") return;
    if (typeof node.body === "string") {
      const author = node.user?.login ?? node.author?.login ?? null;
      found.push({ body: node.body, author: typeof author === "string" ? author : null });
    }
    for (const value of Object.values(node)) walk(value);
  };
  walk(parsed);
  return found;
}


/**
 * Review-comment activity in the transcript since `since`.
 *
 * Returns `{ fetched, human, anomalies }`: whether any comment content
 * arrived this turn (a comment-fetching tool result, or a webhook
 * activity block carrying comment bodies), whether any of it was
 * written by a human, and where the footer contract itself looks
 * broken.
 *
 * Who is a human: with `agents` configured — the forge accounts the
 * agent posts as — the ACCOUNT decides, and the footer only covers
 * comments whose author is unknown. Account identity is the stronger
 * signal exactly when principal and agent are distinct accounts; the
 * footer alone would misread a footer change or a wrong-account post.
 * Both of those are returned as anomalies (`footer-drift`: an agent
 * account posting without the footer; `foreign-footer`: any other
 * account carrying it), for the caller to fail loudly on when the
 * accounts are configured.
 *
 * Deliberately a heuristic, and a conservative one: bodies are found
 * by their JSON field, so comment text a wrapper reformats into prose
 * is missed rather than guessed at. The observer runs this
 * observe-first; only a contradiction with what the turn itself
 * declared — or a configured account anomaly — is allowed to block.
 */
export function reviewSignals(text, since, agents = []) {
  const boundary = since ? new Date(since).getTime() : null;
  const wanted = new Set();
  const carried = [];
  for (const line of String(text).split("\n")) {
    if (!line.trim()) continue;
    let record;
    try {
      record = JSON.parse(line);
    } catch {
      continue;
    }
    if (boundary && record?.timestamp && new Date(record.timestamp).getTime() < boundary) {
      continue;
    }
    const content = record?.message?.content;
    if (record?.type === "assistant" && Array.isArray(content)) {
      for (const block of content) {
        if (block?.type !== "tool_use") continue;
        if (!REVIEW_FETCH.test(block.name ?? "")) continue;
        if (!REVIEW_METHODS.has(block.input?.method)) continue;
        wanted.add(block.id);
      }
      continue;
    }
    if (record?.type !== "user") continue;
    if (typeof content === "string") {
      if (content.includes("<github-webhook-activity>")) carried.push(content);
      continue;
    }
    if (!Array.isArray(content)) continue;
    for (const block of content) {
      if (block?.type === "text" && block.text?.includes("<github-webhook-activity>")) {
        carried.push(block.text);
      }
      if (block?.type !== "tool_result" || !wanted.has(block.tool_use_id)) continue;
      const inner = block.content;
      if (typeof inner === "string") carried.push(inner);
      if (Array.isArray(inner)) {
        for (const piece of inner) {
          if (piece?.type === "text" && typeof piece.text === "string") carried.push(piece.text);
        }
      }
    }
  }
  const known = new Set(agents.map((name) => String(name).toLowerCase()));
  let fetched = false;
  let human = false;
  const anomalies = [];
  for (const chunk of carried) {
    for (const { body, author } of commentsIn(chunk)) {
      fetched = true;
      const footered = body.includes(ATTRIBUTION_FOOTER);
      const agent = author && known.has(author.toLowerCase());
      if (known.size && author) {
        if (!agent) human = true;
        if (agent && !footered) anomalies.push({ kind: "footer-drift", author });
        if (!agent && footered) anomalies.push({ kind: "foreign-footer", author });
        continue;
      }
      if (!footered) human = true;
    }
  }
  return { fetched, human, anomalies };
}


const TICKET_WRITE = /(issue_write|add_issue_comment|sub_issue_write)$/;

const PR_WRITE = /(create_pull_request|update_pull_request)$/;

// The forge's canonical keywords, as the ticket-reference gate spells
// them: ALL CAPS, then `#n` or `owner/repo#n`.
const PR_BODY_REF = /\b(?:CLOSES|FIXES|ADVANCES)\s+(?:([\w.-]+\/[\w.-]+))?#(\d+)/g;


/**
 * Tickets the transcript shows being written to since `since`, as
 * lowercase `owner/repo#n` strings.
 *
 * The truth source for the tickets-updated check: an issue-writing
 * tool call names its owner, repo and issue number in its own input,
 * so the declared set diffs against actual calls without touching the
 * network. Only writes count — reading a ticket is not updating it.
 *
 * Two writes carry no number in the call (skills#181). A create call's
 * number exists only in its tool result, so the call is remembered by
 * its tool_use id and the result's `/issues/<n>` completes it. A PR
 * body with a canonical CLOSES/FIXES/ADVANCES reference writes the
 * ticket's timeline through the forge, so the ticket heard about the
 * turn without a comment of its own.
 */
export function ticketWrites(text, since) {
  const boundary = since ? new Date(since).getTime() : null;
  const written = new Set();
  const pendingCreates = new Map();
  for (const line of String(text).split("\n")) {
    if (!line.trim()) continue;
    let record;
    try {
      record = JSON.parse(line);
    } catch {
      continue;
    }
    if (boundary && record?.timestamp && new Date(record.timestamp).getTime() < boundary) {
      continue;
    }
    const content = record?.message?.content;
    if (!Array.isArray(content)) continue;
    if (record.type === "user") {
      for (const block of content) {
        if (block?.type !== "tool_result") continue;
        const repo = pendingCreates.get(block.tool_use_id);
        if (!repo) continue;
        pendingCreates.delete(block.tool_use_id);
        const n = /\/issues\/(\d+)/.exec(resultText(block.content))?.[1];
        if (n) written.add(`${repo}#${n}`.toLowerCase());
      }
      continue;
    }
    if (record.type !== "assistant") continue;
    for (const block of content) {
      if (block?.type !== "tool_use") continue;
      const input = block.input ?? {};
      if (!input.owner || !input.repo) continue;
      const repo = `${input.owner}/${input.repo}`;
      if (PR_WRITE.test(block.name ?? "")) {
        for (const match of String(input.body ?? "").matchAll(PR_BODY_REF)) {
          written.add(`${match[1] ?? repo}#${match[2]}`.toLowerCase());
        }
        continue;
      }
      if (!TICKET_WRITE.test(block.name ?? "")) continue;
      const n = input.issue_number ?? input.issueNumber ?? input.number;
      if (Number.isInteger(n)) {
        written.add(`${repo}#${n}`.toLowerCase());
      } else if (input.method === "create" && block.id) {
        pendingCreates.set(block.id, repo);
      }
    }
  }
  return written;
}


/** The text of a tool_result block, whichever shape the harness used. */
function resultText(content) {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content.map((b) => (typeof b === "string" ? b : (b?.text ?? ""))).join("\n");
}


/** Refs the ledger knows to be PRs: every `pr` a thread event carried. */
export function knownPrs(events) {
  const known = new Set();
  for (const event of events) if (event.pr) known.add(event.pr);
  return known;
}


/**
 * The forge a shortcode config names, with GitHub defaults.
 *
 * The config file is either flat — shortcode → owner/repo, GitHub
 * assumed — or structured: `{forge, patterns: {ticket, pr}, repos}`,
 * where patterns interpolate `{base}`, `{repo}` and `{n}`. The forge is
 * org configuration and lives in the store beside the map, never in
 * this code: a GitLab org writes its own base and patterns and every
 * canonical form follows — tickets at `/-/issues`, merge requests at
 * `/-/merge_requests` — with nothing here naming a vendor.
 */
export function forgeOf(config) {
  const repos = config.repos ?? config;
  const base = config.forge ?? "https://github.com";
  const patterns = {
    ticket: config.patterns?.ticket ?? "{base}/{repo}/issues/{n}",
    pr: config.patterns?.pr ?? "{base}/{repo}/pull/{n}",
  };
  const url = (sigil, repo, num) =>
    patterns[sigil === "!" ? "pr" : "ticket"]
      .replaceAll("{base}", base)
      .replaceAll("{repo}", repo)
      .replaceAll("{n}", String(num));
  return { repos, url };
}


/**
 * Style violations in `prose` under the response-hygiene rules (#99).
 *
 * The style: tickets and PRs appear as shortcode refs — `XXX#n` for
 * tickets, `XXX!n` for PRs — each a markdown link to the forge page
 * its sigil implies, built by `forgeOf` from the same config that
 * defines the shortcodes. Returned violations carry the offending
 * token, the canonical form when one is derivable, and why. Pure text
 * in, plain data out; the heartbeat owns blocking and the exercise.
 */
export function refViolations(prose, config, prs = new Set()) {
  const found = [];
  const { repos: shortcodes, url: forgeUrl } = forgeOf(config);
  const repoOf = new Map(Object.entries(shortcodes).map(([short, repo]) => [repo, short]));
  const canonical = (short, sigil, num) =>
    `[${short}${sigil}${num}](${forgeUrl(sigil, shortcodes[short], num)})`;
  // The sigil a ref should carry: `!` when the ledger knows the number
  // as a PR, otherwise whatever was written — the hook has no API, and
  // guessing kinds it cannot verify would block on truths.
  const rightSigil = (short, sigil, num) =>
    prs.has(`${shortcodes[short]}#${num}`) ? "!" : sigil;

  // Links first, validated and then blanked so the bare-token scan
  // cannot re-flag their labels.
  let rest = prose.replace(/\[([^\]\n]*)\]\(([^()\s]+)\)/g, (whole, label, url) => {
    const ref = /^([A-Za-z][\w-]*)([#!])(\d+)$/.exec(label);
    if (!ref) {
      const long = /^([\w.-]+\/[\w.-]+)[#!](\d+)$/.exec(label);
      if (long && repoOf.has(long[1])) {
        const short = repoOf.get(long[1]);
        const sigil = whole.includes("!") && !whole.includes("#") ? "!" : label.includes("!") ? "!" : "#";
        found.push({
          token: label,
          canonical: canonical(short, rightSigil(short, sigil, long[2]), long[2]),
          why: "prose uses the shortcode, not the full repository path",
        });
      }
      return " ";
    }
    const [, short, sigil, num] = ref;
    if (!shortcodes[short]) {
      found.push({
        token: label,
        canonical: null,
        why: `unknown shortcode — the map defines: ${Object.keys(shortcodes).join(", ")}`,
      });
      return " ";
    }
    const wanted = rightSigil(short, sigil, num);
    if (wanted !== sigil) {
      found.push({
        token: label,
        canonical: canonical(short, wanted, num),
        why: "the ledger records this number as a pull request — the sigil is !",
      });
      return " ";
    }
    if (url !== forgeUrl(sigil, shortcodes[short], num)) {
      found.push({
        token: `[${label}](${url})`,
        canonical: canonical(short, sigil, num),
        why: `the link does not point at the ${sigil === "!" ? "pull request" : "ticket"} the label names`,
      });
    }
    return " ";
  });

  // Bare full-path refs: the form PR bodies and ledger events use,
  // where GitHub autolinks it. Prose gets the shortcode.
  rest = rest.replace(/\b([\w.-]+\/[\w.-]+)([#!])(\d+)\b/g, (token, repo, sigil, num) => {
    const short = repoOf.get(repo);
    found.push({
      token,
      canonical: short ? canonical(short, rightSigil(short, sigil, num), num) : null,
      why: short
        ? "prose uses the linked shortcode form"
        : `no shortcode maps to ${repo} — add one to the map or leave the ref out`,
    });
    return " ";
  });

  // Bare shortcode refs — right vocabulary, missing the link.
  rest = rest.replace(/(?<![\w/[])([A-Za-z][A-Za-z-]*)([#!])(\d+)\b/g, (token, short, sigil, num) => {
    if (!shortcodes[short]) return token;
    found.push({
      token,
      canonical: canonical(short, rightSigil(short, sigil, num), num),
      why: "shortcode refs are markdown links",
    });
    return " ";
  });

  // Repo-less refs. `#n` names nothing across eight repositories.
  for (const bare of rest.matchAll(/(?<![\w#!/])#(\d+)\b/g)) {
    found.push({
      token: bare[0],
      canonical: null,
      why: "a bare number names no repository — use a shortcode ref",
    });
  }
  return found;
}
